numpy.array 常用变量及参数


dtype变量，用来存放数据类型， 创建数组时可以同时指定。shape变量， 存放数组的大小， 这人值是可变的， 只要确保无素个数不变的情况下可以任意修改。（-1为自动适配， 保证个数不变）reshape方法，创建一个改变了形状的数组，与原数组是内存共享的，即都指向同一块内存。 


In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

创建数组的方法

In [3]:
np.array([[1, 2, 3, 4],[4, 5, 6, 7], [7, 8, 9, 10]], dtype=np.float)
np.arange(0,1,0.1) #0到1之间步长为0.1的数组, 数组中不包含1
np.linspace(0, 1, 5) # 开始：0， 结束1, 元素个数 5。 array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])
np.logspace(0, 1, 5) # 开始：0， 结束1, 元素个数 5. array([ 10**0.  ,  10**0.25,  10**0.5 ,  10**0.75,  10**1.  ])
                     # 结果是 array([  1.        ,   1.77827941,   3.16227766,   5.62341325,  10.        ])
 
s = 'abcdefg'
np.fromstring(s, dtype=np.int8)
 
def func2(i, j):
    return (i+1) * (j+1)
np.fromfunction(func2, (9,9))
 
np.ones((2, 2))
np.zeros((2, 2))
np.eye(2)
 
#创建二维数组：
np.arange(0, 60, 10).reshape(-1, 1) + np.arange(0, 6)


array([[  1.,   2.,   3.,   4.],
       [  4.,   5.,   6.,   7.],
       [  7.,   8.,   9.,  10.]])

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

array([  1.        ,   1.77827941,   3.16227766,   5.62341325,  10.        ])

array([ 97,  98,  99, 100, 101, 102, 103], dtype=int8)

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.],
       [  3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.],
       [  4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.],
       [  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.],
       [  6.,  12.,  18.,  24.,  30.,  36.,  42.,  48.,  54.],
       [  7.,  14.,  21.,  28.,  35.,  42.,  49.,  56.,  63.],
       [  8.,  16.,  24.,  32.,  40.,  48.,  56.,  64.,  72.],
       [  9.,  18.,  27.,  36.,  45.,  54.,  63.,  72.,  81.]])

array([[ 1.,  1.],
       [ 1.,  1.]])

array([[ 0.,  0.],
       [ 0.,  0.]])

array([ 0.,  0.,  0.,  0.,  0.])

array([[ 1.,  0.],
       [ 0.,  1.]])

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

# 数据读取

通过下标范围获取数据： 与python list对象操作一致。 不同点是这方法获取的数组与原数组是内存共享的。

通过整数序列获取新数组：例 x[[3,2,3,2] ], 产生新数组， 内存不共享

使用布尔数组获取数据：例: x[np.array([True, False, True, False, False])] 或 x[x>0.5],
 返回True对应的数字。


In [7]:
x=np.arange(10)
y=x[::-1]
x
y
y[0] = 100
x

In [11]:
z=x[1:5]
z
z[2]=-1
x

array([1, 2, 3, 4])

array([  0,   1,   2,  -1,   4,   5,   6,   7,   8, 100])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 100])